### PR TITLE
fix for value filtering bug report

### LINKED ISSUE #289: when filtering propertyName for values lets some sneak in, w/ collapse them
```r
wg <- geoknife::webgeom(url="http://cida.usgs.gov/nwc/geoserver/NWC/ows", geom="NWC:gagesii_basins", attribute="gage_id")
head(geoknife::query(wg,'values'))
[1] "101013500" "201017550" "301021470" "401021480" "501022260" "601022330"
```
when the first values of `gage_id` should be 
```r
[1] "01013500" "01017550" "01021470" "01021480" "01022260" "01022330"
```
What is happening is the http://cida.usgs.gov/nwc/geoserver/NWC/ows?service=WFS&version=1.1.0&request=GetFeature&typename=NWC:gagesii_basins&propertyname=gage_id&maxFeatures=5
query includes `gage_id` but also `ogc_fid`, which are collapsed together.

### PR DESCRIPTION
**Pull request by jread-usgs**
fixes #289 

@dblodgett-usgs can you take a quick look? Just adding a small bit to the xpath

### CODE REVIEW

File: R/query-webgeom.R [hunk 1]
```diff
@@ -21,7 +21,7 @@ setMethod(f = "query",signature("webgeom",'character'),
               }
               url <- sprintf('%s?service=WFS&version=%s&request=GetFeature&typename=%s&propertyname=%s',
                              url(.Object), version(.Object), geom(.Object), .Object@attribute)
-              input_list[['key']] = geom(.Object)
+              input_list[['key']] <- sprintf("%s/*[local-name()='%s']", geom(.Object), .Object@attribute)
```
Comment (dblodgett-usgs) [inline R/query-webgeom.R]: Can't say I'm entirely sure what I'm looking at here... But if this is grabbing the desired attribute explicitly rather than assuming that only the requested attribute came back, then 👍

Comment (jread-usgs) [inline R/query-webgeom.R]: yep, exactly. this `*[local-name()='%s']` allows us to match w/o the namespace prefix. So I am really just being explicit about *which* attribute instead of assuming only one comes back. That assumption was fine before because we specify which propertyName to return, but that other attribute was coming in too for this case.
